(function(f){var m=window.AmazonUIPageJS||window.P,k=m._namespace||m.attributeErrors,b=k?k("MarsDeviceUpgraderAssets",""):m;b.guardFatal?b.guardFatal(f)(b,window):b.execute(function(){f(b,window)})})(function(f,m,k){f.when("A","ready").register("UCC-Constants",function(){return{DROPDOWN_SELECT_EVENT:"a:dropdown:customerDeviceDropdown:select",UCC_SEE_MORE_ACTION:"ucc-see-more-",UCC_SEE_LESS_ACTION:"ucc-see-less-",Identifiers:{DROPDOWN_ID:"customerDeviceDropdown",CUSTOMER_IMAGE_ID:"#customer-ucc-image",
TITLE_TEXT_ID:"#customer-ucc-title-text",ACCOUNT_NAME_ID:"#customer-account-name",REVIEWS_DIV:"#ucc-customer-has-reviews-div",NO_REVIEWS_DIV:"#ucc-customer-no-reviews-div",DEVICE_STARS_PREFIX:"#customer-ucc-review-stars-",CUSTOMER_DEVICE_REVIEWS_LINK_ID:"#customer-ucc-review-link",CUSTOMER_ATTRIBUTE_PREFIX_ID:"ucc-customer-device-",UCC_STICKY_TABLE_HEADER:".ucc-sticky-table th",UCC_ATTRIBUTE_TABLE_HEADER:".ucc-attribute-table th",UCC_MOBILE_TABLE_ROWS:".ucc-mobile-table \x3e tbody \x3e tr",UCC_CONTENT_ROW:"#uccContentRow",
UCC_TITLE_ROW:"#uccTitleRow",UCC_V2_SEE_MORE_BUTTON_TEMPLATE:"#ucc-see-more-button-",UCC_V2_SEE_LESS_BUTTON_TEMPLATE:"#ucc-see-less-button-",UCC_V2_WIDGET_WRAPPER_TEMPLATE:"ucc-v2-widget-wrapper-mobile-",UCC_V2_THEAD_TEMPLATE:".ucc-v2-widget__image-row--mobile-",UCC_V2_TABLE_TEMPLATE:".ucc-v2-widget__table--mobile-",UCC_V2_ATTRIBUTE_TITLES_TEMPLATE:".ucc-v2-widget__table__col__container__attribute__title--mobile-",UCC_V2_ATTRIBUTE_SECONDARY_ATTRIBUTE_TEMPLATE:".ucc-v2-widget__table__col__container__attribute--mobile-secondary-",
UCC_V2_ATTRIBUTE_COLUMN_TEMPLATE:".ucc-v2-widget__table__col-",UCC_V2_IMAGE_COLUMN_TEMPLATE:".ucc-v2-widget__image-row__col-",UCC_V2_IMAGE_COLUMN_LAST_TEMPLATE:".ucc-v2-widget__image-row__col--last-",UCC_V2_WIDGET_CLASS:".ucc-v2-widget--mobile",UCC_V2_NON_PAGE_ASIN_IMAGE_HEADERS_TEMPLATE:".ucc-v2-widget__image-row__col--not-page-asin-",UCC_V2_NON_PAGE_ASIN_STICKY_BORDER_CLASS:"ucc-v2-widget__image-row__col--not-page-asin-sticky"}}});"use strict";f.when("A","ready").register("UCC-V2-Config",function(){return{RTL:!1}});
"use-strict";f.when("A","UCC-Constants","a-truncate").register("UCC-Base-Page",function(b,a,f){return b.createClass({init:function(){this._curentReviewStarsID=a.Identifiers.DEVICE_STARS_PREFIX+"aui"},setCustomerProducts:function(a){this._currentDevice=a[0];this._customerDevices=a},getCurrentCustomerDevice:function(){return this._currentDevice},setCurrentCustomerDevice:function(a){this._currentDevice=this._customerDevices[a]},updateCustomerDeviceToPage:function(d,q){b.$(a.Identifiers.CUSTOMER_IMAGE_ID).attr("src",
this._currentDevice.image);b.$(a.Identifiers.CUSTOMER_IMAGE_ID).attr("alt",this._currentDevice.title);b.$(a.Identifiers.TITLE_TEXT_ID).text(this._currentDevice.title);var c=b.$(a.Identifiers.ACCOUNT_NAME_ID);c.hasClass("a-truncate")&&(b.$(c).find(".a-truncate-full").text(this._currentDevice.accountName),f.get(a.Identifiers.ACCOUNT_NAME_ID).update());if(this._currentDevice.averageCustomerReviews.value){c=this._currentDevice;var m=a.Identifiers.DEVICE_STARS_PREFIX+c.averageCustomerReviews.value.averageRating.fullStarCount;
5!=c.averageCustomerReviews.value.averageRating.fullStarCount&&c.averageCustomerReviews.value.averageRating.hasHalfStar&&(m+="-5");c=m;b.$(c).find("span").text(this._currentDevice.averageCustomerReviews.value.averageRating.displayString);b.$(a.Identifiers.CUSTOMER_DEVICE_REVIEWS_LINK_ID).attr("href","/product-reviews/"+this._currentDevice.asin+"?ref\x3d"+this._currentDevice.customerReviewsRefTag);b.$(a.Identifiers.CUSTOMER_DEVICE_REVIEWS_LINK_ID).text("("+this._currentDevice.averageCustomerReviews.value.reviewCount.displayString+
")");b.$(this._curentReviewStarsID).removeClass("do-display");b.$(this._curentReviewStarsID).addClass("do-not-display");this._curentReviewStarsID=c;b.$(c).removeClass("do-not-display");b.$(c).addClass("do-display");b.$(a.Identifiers.NO_REVIEWS_DIV).attr("class","do-not-display");b.$(a.Identifiers.REVIEWS_DIV).attr("class","do-display")}else b.$(a.Identifiers.REVIEWS_DIV).attr("class","do-not-display"),b.$(a.Identifiers.NO_REVIEWS_DIV).attr("class","do-display");for(var g in d)d.hasOwnProperty(g)&&
(c=d[g].replace(/([^A-Za-z0-9/-/_/./:])/g,"-"),"check"===this._currentDevice.merchandisedData[d[g]]?document.getElementById(a.Identifiers.CUSTOMER_ATTRIBUTE_PREFIX_ID+c).outerHTML="\x3cimg alt\x3d'check mark' src\x3d"+q+"class\x3d'ucc-check-mark' id\x3d"+a.Identifiers.CUSTOMER_ATTRIBUTE_PREFIX_ID+c+"\x3e":"IMG"===document.getElementById(a.Identifiers.CUSTOMER_ATTRIBUTE_PREFIX_ID+c).tagName?document.getElementById(a.Identifiers.CUSTOMER_ATTRIBUTE_PREFIX_ID+c).outerHTML="\x3cspan id\x3d"+a.Identifiers.CUSTOMER_ATTRIBUTE_PREFIX_ID+
c+" /\x3e":document.getElementById(a.Identifiers.CUSTOMER_ATTRIBUTE_PREFIX_ID+c).innerText=this._currentDevice.merchandisedData[d[g]])}})});f.when("A","UCC-Constants","UCC-Base-Page").execute("UCC-Builder",function(b,a,g){var d=new g;b.on(a.DROPDOWN_SELECT_EVENT,function(a){d.getCurrentCustomerDevice()||d.setCustomerProducts(JSON.parse(b.state("uccCustomerProducts").jsonData));var c=b.state("uccMerchAttributes").jsonData,g=b.state("uccCheckMarkURL").jsonData;d.setCurrentCustomerDevice(parseInt(a.value)-
1);d.updateCustomerDeviceToPage(c,g)})});"use strict";f.when("A","UCC-Constants").execute("UCC-Render",function(b,a){function g(){var d=b.$(a.Identifiers.UCC_ATTRIBUTE_TABLE_HEADER).outerHeight(!0);b.$(a.Identifiers.UCC_STICKY_TABLE_HEADER).height(d);b.$(a.Identifiers.UCC_MOBILE_TABLE_ROWS).each(function(d){if(b.$(a.Identifiers.UCC_CONTENT_ROW+d).height()>b.$(a.Identifiers.UCC_TITLE_ROW+d).height()){var c=b.$(a.Identifiers.UCC_CONTENT_ROW+d).outerHeight(!0);b.$(a.Identifiers.UCC_TITLE_ROW+d).height(c)}else c=
b.$(a.Identifiers.UCC_TITLE_ROW+d).outerHeight(!0),b.$(a.Identifiers.UCC_CONTENT_ROW+d).height(c)})}g();b.on("a:pageUpdate",g)});"use strict";f.when("A","UCC-Constants","UCC-V2-Config","afterLoad").execute("UCC-Render-V2",function(b,a,g){function d(a,b,c){var d=a;a.endsWith("-")||(d+="-");b&&(d+=b);if(0==c||c)d+="-"+c;return d}function f(){if(c("div[[id^\x3d'"+a.Identifiers.UCC_V2_WIDGET_WRAPPER_TEMPLATE+"']").length){var f=[],g=!0;if(m.ResizeObserver){var k=new m.ResizeObserver(function(){f.forEach(function(a){a()})});
k.observe(document.body)}else g=!1;c("div[[id^\x3d'"+a.Identifiers.UCC_V2_WIDGET_WRAPPER_TEMPLATE+"']").each(function(){var e=this.id,k="#"+e;e=e.split(a.Identifiers.UCC_V2_WIDGET_WRAPPER_TEMPLATE)[1];var t=d(a.Identifiers.UCC_V2_SEE_MORE_BUTTON_TEMPLATE,e),I=d(a.Identifiers.UCC_V2_SEE_LESS_BUTTON_TEMPLATE,e),q=d(a.Identifiers.UCC_V2_THEAD_TEMPLATE,e),p=d(a.Identifiers.UCC_V2_TABLE_TEMPLATE,e),J=d(a.Identifiers.UCC_V2_ATTRIBUTE_COLUMN_TEMPLATE,e),u=d(a.Identifiers.UCC_V2_IMAGE_COLUMN_TEMPLATE,e),
v=d(a.Identifiers.UCC_V2_IMAGE_COLUMN_LAST_TEMPLATE,e),n=d(a.Identifiers.UCC_V2_NON_PAGE_ASIN_IMAGE_HEADERS_TEMPLATE,e),l=c(k),w=l.height(),h=c(q),z=c(t),A=c(I);t=c(J);k=c(u);v=c(v);var B=c(p),C=c(n);b.declarative(d(a.UCC_SEE_MORE_ACTION,e),"click",function(a){l.addClass("ucc-v2-widget__wrapper--expanded");l.removeClass("ucc-v2-widget__wrapper--collapsed");z.hide();A.show();w=l.height()});b.declarative(d(a.UCC_SEE_LESS_ACTION,e),"click",function(a){l.removeClass("ucc-v2-widget__wrapper--expanded");
l.addClass("ucc-v2-widget__wrapper--collapsed");A.hide();z.show();w=l.height()});n=t.innerWidth();u=k.innerWidth();e=n;p=k.length;2<p&&150>e&&(e=150);n!=u&&k.css("flex","0 0 "+e+"px");n=e+1;2>=p&&(n=e+2);v.css("flex","0 0 "+n+"px");if(null!=h.offset()&&g){var D=h.offset().top,x=!1,E=l.offset().top,y=function(){x?H?h.css("left",14+l.scrollLeft()+r+"px"):h.css("left",14-l.scrollLeft()+r+"px"):h.css("left","0px")},F=function(){h.css("position","relative");h.css("top","0");B.css("margin-top","0");h.css("left",
"0px");C.removeClass(a.Identifiers.UCC_V2_NON_PAGE_ASIN_STICKY_BORDER_CLASS)},G=function(){var b=c(m).scrollTop();D<b&&w+E-h.height()>b?(x=!0,h.css("position","fixed"),h.css("top","0"),B.css("margin-top",h.height()+"px"),C.addClass(a.Identifiers.UCC_V2_NON_PAGE_ASIN_STICKY_BORDER_CLASS)):(x=!1,F())};f.push(function(){h.length&&(F(),D=h.offset().top,E=l.offset().top,G(),y())});l.scroll(y);c(m).scroll(function(){G();y()})}})}}var c=b.$,r=0,H=g.RTL!==k?g.RTL:!1;r=function(){if(c("div[[id^\x3d'"+a.Identifiers.UCC_V2_WIDGET_WRAPPER_TEMPLATE+
"']").length){var b=c(a.Identifiers.UCC_V2_WIDGET_CLASS).offset();if(b)return b.left}return 14}();f();b.on("a:pageUpdate",f)})});