(function(c){var h=window.AmazonUIPageJS||window.P,g=h._namespace||h.attributeErrors,a=g?g("CommonDetailPageScripts",""):h;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,h,g){c.when("jQuery","jumpLink").execute(function(a,b){var n=a("#miniATFUDP"),d=0;0<n.length&&(d=n.height()+9);0<a("#reviewStarsLinkedCustomerReviews").length&&b.bind("#reviewStarsLinkedCustomerReviews",10,d);0<a("#askATFLink").length&&b.bind("#askATFLink",10,d);c.when("cf").execute(function(c){0<
a("#important-information a[href\x3d'#legal-disclaimer']").length&&b.bind("#important-information a[href\x3d'#legal-disclaimer']",10,d,!0)});b.bind("#seeMoreDetailsLink",300,d)});"use strict";c.when("A","jQuery","ImageBlockATF","jumpLink","cf").register("miniATFUtils",function(a,b,n,d){function g(a){q&&!a||r||(a=(new Date).getTime()-w,a=50>a?50-a:10,q=1,q=0,w=(new Date).getTime(),setTimeout(function(){var a=t.scrollTop(),k=b("#miniATFUDP");if(0<k.length){var e=x;if("T1"===e){e=b("#sims_fbt");if(0>=
e.length||0>=e.height())e=b("#buyxgety_feature_div");var f=e;e=Number.MAX_VALUE;if(f&&0<f.length){var c=f.height();f=f.offset();c&&f&&(e=f.top+c)}e=Math.min(e,1200)}else if("T2"===e){e="#product-details-grid_feature_div #prodDetails #important-information_feature_div #importantInformation #detail-bullets #detail_bullets_id #technical-data #technicalSpecifications_feature_div #productDescription #product-description-iframe #dpx-btf-hlcx-comparison_feature_div #HLCXComparisonWidget_feature_div".split(" ");
f=Number.MAX_VALUE;for(c=0;c<e.length;c++){var d=b(e[c]);if(d&&0<d.length&&0<d.height()){var m=Number.MAX_VALUE;d&&0<d.length&&(d=d.offset())&&(m=d.top);m<f&&(f=m)}}e=Math.min(f,1700)-100}else e=void 0;a>e?!u&&k.is(":hidden")&&(k.removeClass("a-hidden"),k.slideDown(200)):(k.slideUp(200),u=0)}},a))}d=b("#miniATFUDP");var y=b("#miniATFPartialSelection")[0],l=b(".twister-dropdown-highlight")[0];if(!(0>=d.length)){var u=0,w=0,q=0,p={},r=0,v=0,x="T2";p.setMiniATFShowHeight=function(b){x=b};p.setMiniATFScrollUpHeight=
function(a){v=0;"T1"===a&&(a=b("#productTitle"),0<a.length&&(a=a.offset())&&(v=a.top-20))};b("body").delegate(".go-to-top","click",function(){b("body, html").animate({scrollTop:v},300);u=1;y&&l&&(b(l).removeClass("transparentTwisterDropdownBorder"),b(l).addClass("highlightTwisterDropdownBorder"));return!1});y&&l&&b(l).click(function(){b(this).addClass("transparentTwisterDropdownBorder");b(this).removeClass("highlightTwisterDropdownBorder")});var t=b(h);t.scroll(function(){g(0)});t.resize(function(){g(1)});
c.when("ImageBlockBTF").execute(function(d){var c=function(a){var m=a.getState().selected_variations;if(m){var c="",e=a.getState().variation_display_labels;b.each(d.visualDimensions,function(a,b){a=1===d.gIsNewTwister?b:e[b];m[a]&&(c+=" "+m[a])});return c&&c.substring(1)}},g=d.defaultColor,e=g,f=d.landingAsinColor,h,k=b("#miniATF_image");0<k.length&&(h=k.attr("src"));p.updateMiniATFDiv=function(){r=0;var a=b("#miniATF_image");0<a.length&&h&&a.attr("src",h)};a.on("image-block-twister-swatch-click",
function(a,b,k,l){r=1;a=(a=l?l:c(b))&&""!==a?a:g;a===f&&(a=g);a!==e&&(h=(b=a!==g&&a!==f?d:n)&&b.colorImages&&b.colorImages[a]&&0<b.colorImages[a].length&&b.colorImages[a][0]?b.colorImages[a][0].large:null,e=a)})});return p}});"use strict";c.when("ueCount","jQuery").execute(function(a,b){b("#miniATF_BackToTopLink").click(function(){a.incrementCounterByOne("sl_back_to_top_button_click_count")})});"use strict";c.when("jQuery","dp-util-cookie","cf").execute(function(a,b){"000-0000000-8675309"===a("#addToCart").find('input[name\x3d"session-id"]').val()&&
a("#addToCart").find('input[name\x3d"session-id"]').val(b("session-id"))});"use strict";c.when("A","ready").execute(function(a){a=a.$;var b=a("#seeMoreDetailsLink"),c=a("#prodDetails");b.length&&c.length&&(b.bind("keydown",function(a){13===a.keyCode&&(c.attr("tabindex","-1"),c.focus())}),b.bind("click",function(a){c.attr("tabindex","-1");c.focus()}))})});
/* ******** */
(function(g){var e=window.AmazonUIPageJS||window.P,n=e._namespace||e.attributeErrors,a=n?n("DetailPageClimatePledgeFriendlyNewAssets",""):e;a.guardFatal?a.guardFatal(g)(a,window):a.execute(function(){g(a,window)})})(function(g,e,n){g.when("A","climate-pledge-friendly-csm-counters").register("cpf-dpx-handlers",function(a,c){function d(){return a.capabilities.isAmazonApp?"map":a.capabilities.tablet?"twb":a.capabilities.mobile?"mwb":"dsk"}a.declarative("CPF-ATF-LandingPageLink","click",{allowLinkDefault:!0},
function(a){c.incrementCounter("cpf_dp_"+d()+"_dpcd_aflk")});a.declarative("CPF-BTF-LandingPageLink","click",{allowLinkDefault:!0},function(a){c.incrementCounter("cpf_dp_"+d()+"_dpcd_bflk")});a.declarative("CPF-OpenExternalLink","click",function(l){var h=l.$currentTarget[0].firstChild.href;c.incrementCounter("cpf_dp_"+d()+"_dpcd_excf");a.capabilities.isAmazonApp?g.when("mash").execute(function(a){e.location=h}):e.open(h,"_blank")});g.when("A").execute(function(a){a.on("a:image:lazyLoaded",function(a){a.hasClass("climatePledgeFriendlyLazyload")&&
c.recordLazyLoad()});a.on("a:image:load:cpf-leaf",function(){c.recordImageLoad()})});c.recordLatency()});"use strict";g.when("dp-latency-marker").register("climate-pledge-friendly-csm-counters",function(){return{incrementCounter:function(a,c){c=c||1;c=(ue.count(a)||0)+c;ue.count(a,c)},recordLatency:function(){"function"===typeof e.uet&&e.uet("bb","climate-pledge-friendly-dpx",{wb:1});"function"===typeof e.uet&&e.uet("x1","climate-pledge-friendly-dpx",{wb:1});"function"===typeof e.uex&&e.uex("ld",
"climate-pledge-friendly-dpx",{wb:1})},recordClick:function(){"function"===typeof e.uet&&e.uet("af","climate-pledge-friendly-dpx-click",{wb:1});"function"===typeof e.uex&&e.uex("ld","climate-pledge-friendly-dpx-click",{wb:1})},recordImageLoad:function(){"function"===typeof e.uet&&e.uet("be","climate-pledge-friendly-dpx-image-loading",{wb:1});"function"===typeof e.uex&&e.uex("ld","climate-pledge-friendly-dpx-image-loading",{wb:1})},recordLazyLoad:function(){"function"===typeof e.uet&&e.uet("cf","climate-pledge-friendly-dpx-image-loading",
{wb:1});"function"===typeof e.uex&&e.uex("ld","climate-pledge-friendly-dpx-image-loading",{wb:1})}}});g.when("dp-latency-marker").register("cpf-dpx-common-constants",function(){return{ATTRIBUTION_STRING:"DetailPageClimatePledgeFriendly",EVENT_ID_BOTTOM_SHEET_SHOW:"cpf-dpx-sheet",EVENT_ID_BOTTOM_SHEET_SECONDARY_SHOW:"cpf-dpx-sheet-secondary",EVENT_ID_BOTTOM_SHEET_SECONDARY_BACK:"cpf-dpx-sheet-secondary-back",EVENT_ID_SIDE_SHEET_SHOW:"cpf-dpx-sidesheet-open",EVENT_ID_SIDE_SHEET_HIDE:"cpf-dpx-sidesheet-close",
EVENT_ID_SIDE_SHEET_CAPTURE:"cpf-dpx-sidesheet-capture",EVENT_ID_SIDE_SHEET_SECONDARY_SHOW:"cpf-dpx-sidesheet-secondary",EVENT_ID_SIDE_SHEET_SECONDARY_BACK:"cpf-dpx-sidesheet-secondary-back",EVENT_ID_SUST_CARD_TRIGGER:"cpf-dpx-wl-trigger",EVENT_ID_SUST_CARD_ADJUST:"cpf-dpx-sust-card-adjust",SELECTOR_BOTTOM_SHEET_CONTAINER:".cpf-dpx-container-bottom-sheet",SELECTOR_BOTTOM_SHEET_CONTAINER_SECONDARY:".cpf-dpx-container-bottom-sheet-secondary",SELECTOR_BOTTOM_SHEET_SECONDARY_BACK_BUTTON:".cpf-dpx-detail-view-secondary-back",
SELECTOR_BOTTOM_SHEET_CAROUSEL:".cpf-dpx-bottom-sheet-carousel",SELECTOR_PROGRAM_STICKY_FOOTER:".cpf-dpx-sticky-footer",SELECTOR_SIDE_SHEET_SECONDARY_BACK_BUTTON:".cpf-dpx-detail-view-secondary-back",SIDE_SHEET_CONTAINER_ID:"cpf-dpx-sidesheet-container",SIDE_SHEET_START_ANCHOR_CLASSNAME:"cpf-dpx-sidesheet-anchor-start",SIDE_SHEET_END_ANCHOR_CLASSNAME:"cpf-dpx-sidesheet-anchor-end",CAROUSEL_INITIALIZED_CLASS:"a-carousel-initialized",CAROUSEL_NOT_INITIALIZED_CLASS:"a-carousel-static",KEYCODE_ESCAPE:27,
KEYCODE_TAB:9,SCROLL_CORRECTION_OFFSET:5,SCROLL_EVENT_THROTTLE_MS:150,BOTTOM_SHEET_HEIGHT_CHANGE_DURATION:.3,SCROLL_EVENT_DELAY_MS:1E3,SIDE_SHEET_OPEN_ANIMATION_DELAY_MS:300,SIDE_SHEET_CLOSE_ANIMATION_DELAY_MS:200,MS_CONVERT:1E3,TRIGGER_URI:"/ussx/weblab-trigger?",QC_WEBLAB:"CONSUMABLES_CPF_QUANTIFIABLE_CLAIMS_1080213",SUST_CARD_WEBLAB:"CONSUMABLES_DP_CPF_SUST_CARD_EXP_1244410"}});g.when("A","cpf-dpx-common-constants","cpf-dpx-sidesheet-util","cpf-dpx-trigger-utils","ready").register("cpf-dpx-sidesheet",
function(a,c,d,l){var h=e.ue&&e.ue.count||function(){};a.declarative(c.EVENT_ID_SIDE_SHEET_SHOW,"click",function(b){var e=b.$currentTarget,m;b.data.preloadDomId?(b.data.ctMetric&&h(b.data.ctMetric,1),b.data.qcTrigger&&l.triggerQCWeblab(b.data.qcTrigger,c.QC_WEBLAB),d.preloadSheet(b.data.preloadDomId,b.data.popoverLabel,b.data.closeButtonLabel,!!b.data.removeBackButton),d.showSheet(),a.one("cpf-dpx-sidesheet:afterShow",function(b){a.loadDescendantImagesManually(b.sheet);m=a.now()}),a.one("cpf-dpx-sidesheet:afterHide",
function(){var d;e&&e.length&&(d=e.find("a").first())&&d.length&&d.focus();b.data.dwellMetric&&m&&h(b.data.dwellMetric,(a.now()-m)/c.MS_CONVERT)})):g.log("Sidesheet show error: missing DOM ID for loading","ERROR",c.ATTRIBUTION_STRING)});a.declarative(c.EVENT_ID_SIDE_SHEET_SECONDARY_SHOW,"click",function(b){b.data.preloadDomId&&b.data.previousPreloadDomId?a.$("#"+b.data.preloadDomId).length?(b.data.ctMetric&&h(b.data.ctMetric,1),d.preloadSecondaryContent(b.data.preloadDomId),d.addBackActionData(b.data.ctDwellMetric,
0!==b.$target.length?b.$target.attr("id"):b.data.previousPreloadDomId),d.showSecondaryContent()):(b.data.delayMetric&&h(b.data.delayMetric,1),g.log("Can not find secondary sheetContent by preloadDomId in desktop side sheet","INFO",c.ATTRIBUTION_STRING)):g.log("Sidesheet secondary show error: missing DOM ID for loading","ERROR",c.ATTRIBUTION_STRING)});a.declarative(c.EVENT_ID_SIDE_SHEET_SECONDARY_BACK,"click",function(b){b.data&&b.data.returnFocusId?d.hideSecondaryContent(b.data.returnFocusId):d.hideSecondaryContent();
b.data&&b.data.ctDwellMetric&&b.data.ctDwellStart&&h(b.data.ctDwellMetric,(a.now()-b.data.ctDwellStart)/c.MS_CONVERT)});a.declarative(c.EVENT_ID_SIDE_SHEET_HIDE,"click",function(){d.hideSheet()});a.declarative(c.EVENT_ID_SIDE_SHEET_CAPTURE,"keydown",function(a){"keydown"!==a.type||a.$event.keyCode!==c.KEYCODE_ESCAPE&&a.$event.key!==c.KEYCODE_ESCAPE||d.hideSheet()});a.declarative(c.EVENT_ID_SIDE_SHEET_CAPTURE,"focusin",function(b){b.$target.length&&b.$target.hasClass(c.SIDE_SHEET_END_ANCHOR_CLASSNAME)&&
a.delay(function(){d.focusOnFirst()},0)});a.declarative(c.EVENT_ID_SIDE_SHEET_CAPTURE,"focusout",function(b){b.$target.length&&a.delay(function(){a.$(document.activeElement).hasClass(c.SIDE_SHEET_START_ANCHOR_CLASSNAME)&&d.focusOnLast()},0)});a.on("a:expander:pc_sidesheet_expander:toggle:expand",function(a){a.expander&&a.expander.$expander&&a.expander.$expander.data("eometric")&&h(a.expander.$expander.data("eometric"),1)});a.on(c.EVENT_ID_SUST_CARD_TRIGGER,function(a){"sustExpanderTreatment"in a&&
l.triggerQCWeblab(a.sustExpanderTreatment,c.SUST_CARD_WEBLAB)})});"use strict";g.when("A","jQuery","cpf-dpx-common-constants").register("cpf-dpx-sidesheet-util",function(a,c,d){function e(){return c("#"+d.SIDE_SHEET_CONTAINER_ID)}function h(a){return a.find("#cpf-dpx-sidesheet-content-container")}function b(a){return a.find("#cpf-dpx-sidesheet-background")}function p(a){return a.find("#cpf-dpx-sidesheet-content")}function m(a){return a.find("#cpf-dpx-sidesheet-secondary-content")}function n(b){var d=
e(),f=p(d),g=m(d);a.hide(g);a.show(f);g.attr("aria-hidden","true");f.attr("aria-hidden","false");d.find(".cpf-dpx-sidesheet-anchor-start").focus();b&&(b=c("#"+b),b.length&&b.focus())}return{preloadSheet:function(b,h,k,l){var f=e();b=c("#"+b);f&&0!==f.length||(f=c(document.createElement("div")),f.attr("id",d.SIDE_SHEET_CONTAINER_ID),f.addClass("a-section a-spacing-none"),f.append('\x3cspan class\x3d"a-declarative" data-action\x3d"'+d.EVENT_ID_SIDE_SHEET_CAPTURE+'"\x3e\x3cspan class\x3d"a-declarative" data-action\x3d"cpf-dpx-sidesheet-close" aria-label\x3d"'+
k+'" tabindex\x3d"0"\x3e\x3cdiv id\x3d"cpf-dpx-sidesheet-background" class\x3d"cpf-dpx-sidesheet-background" aria-hidden\x3d"true"\x3e\x3c/div\x3e\x3c/span\x3e\x3cdiv id\x3d"cpf-dpx-sidesheet-content-container" class\x3d"cpf-dpx-sidesheet" aria-modal\x3d"true" role\x3d"dialog" aria-labelledby\x3d"cpf-dpx-sidesheet-label" aria-hidden\x3d"true"\x3e\x3cspan tabindex\x3d"0" class\x3d"'+d.SIDE_SHEET_START_ANCHOR_CLASSNAME+' cpf-dpx-sidesheet-a11y-label"\x3e\x3c/span\x3e\x3cheader\x3e\x3cspan id\x3d"cpf-dpx-sidesheet-label" class\x3d"cpf-dpx-sidesheet-a11y-label aok-block" aria-hidden\x3d"true"\x3e'+
h+'\x3c/span\x3e\x3cbutton class\x3d"a-declarative cpf-dpx-sidesheet-close-button" data-action\x3d"cpf-dpx-sidesheet-close" aria-label\x3d"'+k+'"\x3e\x3cdiv class\x3d"a-icon cpf-dpx-sidesheet-close-icon"\x3e\x3c/div\x3e\x3c/button\x3e\x3c/header\x3e\x3cdiv id\x3d"cpf-dpx-sidesheet-content" aria-hidden\x3d"true"\x3e\x3c/div\x3e\x3cdiv id\x3d"cpf-dpx-sidesheet-secondary-content" aria-hidden\x3d"true"\x3e\x3c/div\x3e\x3cspan tabindex\x3d"0" class\x3d"'+d.SIDE_SHEET_END_ANCHOR_CLASSNAME+' cpf-dpx-sidesheet-a11y-label"\x3e\x3c/span\x3e\x3c/div\x3e\x3c/span\x3e'),
c("body").prepend(f));b&&0!==b.length?(p(f).html(b.html()),l&&p(f).find(d.SELECTOR_SIDE_SHEET_SECONDARY_BACK_BUTTON).parent().remove(),a.loadDescendantImagesManually(f)):g.log("Can not find the sheetContent by preloadDomId in desktop side sheet","ERROR",d.ATTRIBUTION_STRING)},showSheet:function(){var f=e(),g=b(f),k=h(f),l=p(f);a.show(f);n();k.attr("aria-hidden","false");l.attr("aria-hidden","false");f.find(".cpf-dpx-sidesheet-close-button").focus();c("#a-page").attr("aria-hidden","true");c("body").css("overflow",
"hidden");a.show(g);k.show(function(){a.animate(k,{right:"0"},d.SIDE_SHEET_ANIMATION_DELAY_MS,"ease-out",function(){a.trigger("cpf-dpx-sidesheet:afterShow",{sheet:f})})})},hideSheet:function(){var f=e(),g=b(f),k=h(f);k.attr("aria-hidden","true");c("#a-page").attr("aria-hidden","false");c("body").css("overflow","");a.hide(g);a.animate(k,{right:"-500px"},d.SIDE_SHEET_ANIMATION_DELAY_MS,"ease-out",function(){a.hide(f);a.trigger("cpf-dpx-sidesheet:afterHide",{sheet:f})})},addBackActionData:function(b,
c){var f=e();f=m(f).find(d.SELECTOR_SIDE_SHEET_SECONDARY_BACK_BUTTON).parent();b={returnFocusId:c,ctDwellMetric:b,ctDwellStart:a.now()};a.declarative.create(f,d.EVENT_ID_SIDE_SHEET_SECONDARY_BACK,b);f.attr("data-action",d.EVENT_ID_SIDE_SHEET_SECONDARY_BACK);f.attr("data-"+d.EVENT_ID_SIDE_SHEET_SECONDARY_BACK,JSON.stringify(b));f.removeAttr("action-name");f.removeAttr("action-params")},preloadSecondaryContent:function(b){var f=e();b=c("#"+b);f=m(f);b&&0!==b.length?(f.html(b.html()),a.loadDescendantImagesManually(f)):
g.log("Can not find secondary sheetContent by preloadDomId in desktop side sheet","ERROR",d.ATTRIBUTION_STRING)},hideSecondaryContent:n,showSecondaryContent:function(){var b=e(),c=p(b),d=m(b);a.hide(c);a.show(d);d.attr("aria-hidden","false");c.attr("aria-hidden","true");b.find(".cpf-dpx-sidesheet-anchor-start").focus()},focusOnFirst:function(){var a=e();h(a).find("a[href], button").first().focus()},focusOnLast:function(){var a=e();h(a).find("a[href], button").last().focus()}}});g.when("A","cpf-dpx-common-constants").register("cpf-dpx-trigger-utils",
function(a,c){return{triggerQCWeblab:function(d,g){var h="";e.ue&&(h=e.ue.id);d=c.TRIGGER_URI+"weblabValue\x3d"+g+"\x26treatment\x3d"+d+"\x26requestId\x3d"+h;navigator&&navigator.sendBeacon?navigator.sendBeacon(d):a.$.ajax({url:d})}}});g.when("A","cpf-dpx-common-constants").execute("cpf-dpx-bond-initialization",function(a,c){var d=e.ue&&e.ue.count||function(){};a.on("a:expander:cpf_dpx_bond_expander:toggle:expand",function(a){a.expander&&a.expander.$expander&&a.expander.$expander.data("eometric")&&
d(a.expander.$expander.data("eometric"),1)})})});
/* ******** */
